### ISSUE TITLE
Create BDD tests

### ISSUE THREAD

**Issue by biroferenc075** [BME-MIT-IET/iet-hf-2023-koporscho#3]
Using Cucumber

**Comment by biroferenc075** [comment]
Set up the basic framework to enable writing of test cases ebabbff72ba7198f6fadf243a41c43eebf713f8d

**Comment by szaboegon** [comment]
First successful run of Bdd tests 2e3574f40c506cf99f573b8c750b2265474d56d9

**Comment by szaboegon** [comment]
Finished Bdd tests for all the important features 7ac46c3949da5dded2deff50cf53d936c04299ae

**Comment by biroferenc075** [comment]
Cleaned up everything and finished documentation.
f477367e7b5c0379e68bbf41f20cbcb137e09b25 @szaboegon 's contribution,
0531051ec9317d66ef177346a0091d9475d4db12 @biroferenc075 's contribution.
