### ISSUE TITLE
Perform & document manual testing

### ISSUE THREAD

**Issue by biroferenc075** [BME-MIT-IET/iet-hf-2023-koporscho#4]

**Comment by gerinagy10** [comment]
Created a template for the manual testing documentation. Every test should follow this template. a0151364e0c66f4efb0646aa0e049304358f5306

**Comment by gerinagy10** [comment]
Fixed the UI issue which occured in test 2, 3 and 7. c9bb8c244749018a8b38c26605ba1c38ab857631
